<MyLayout>
    BoxLayout:
        #orientation:"horizontal"
        orientation:"vertical"
        padding:50
        spacing:20
        size: root.width,root.height
        Button:
            text:"Hello World"
        Button:
            text:"Hello World"
            size_hint:(None,None)
            pos_hint:{'center_x':0.5}
            width:400
            height:100
        Button:
            text:"Hello World"
            pos_hint:{'center_x':0.5}
            size_hint:(0.5,0.5)